// Generated by nuxt-site-config

import type { SiteConfig, SiteConfigInput, SiteConfigStack } from 'D:/My-assets/otruyen_manga/theme-otruyen/node_modules/nuxt-site-config/dist/runtime/types'

declare module 'nitropack' {
  interface NitroRouteRules {
    site?: SiteConfigInput
  }
  interface NitroRouteConfig {
    site?: SiteConfig
  }
}

declare module 'h3' {
  interface H3EventContext {
    siteConfig: SiteConfigStack
  }
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: SiteConfigInput
  }
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: SiteConfigStack
  }
}

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'site-config:resolve': (siteConfig: SiteConfig) => void
  }
}

export {}
